### ISSUE TITLE
Exit error code 1

### ISSUE THREAD

**Issue by FolkyMcTart** [msieg/deep-visualizer#18]
Using legacy 'setup.py install' for scipy, since package 'wheel' is not installed.
Using legacy 'setup.py install' for librosa, since package 'wheel' is not installed.
Using legacy 'setup.py install' for audioread, since package 'wheel' is not installed.
Using legacy 'setup.py install' for resampy, since package 'wheel' is not installed.
Using legacy 'setup.py install' for moviepy, since package 'wheel' is not installed.
Using legacy 'setup.py install' for proglog, since package 'wheel' is not installed.
Using legacy 'setup.py install' for boto3, since package 'wheel' is not installed.
Installing collected packages: scipy, s3transfer, requests, pillow, packaging, numba, joblib, cffi, appdirs, torch, soundfile, scikit-learn, resampy, proglog, pooch, imageio-ffmpeg, imageio, decorator, boto3, audioread, pytorch-pretrained-biggan, moviepy, librosa
    Running setup.py install for scipy ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\rossp\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Rossp\\AppData\\Local\\Temp\\pip-install-ci31gds8\\scipy_7d706f3f907b40dfb23fcaa90915f082\\setup.py'"'"'; __file__='"'"'C:\\Users\\Rossp\\AppData\\Local\\Temp\\pip-install-ci31gds8\\scipy_7d706f3f907b40dfb23fcaa90915f082\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Rossp\AppData\Local\Temp\pip-record-es5qji36\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\rossp\appdata\local\programs\python\python39\Include\scipy'
         cwd: C:\Users\Rossp\AppData\Local\Temp\pip-install-ci31gds8\scipy_7d706f3f907b40dfb23fcaa90915f082\
    Complete output (146 lines):
    C:\Users\Rossp\AppData\Local\Temp\pip-install-ci31gds8\scipy_7d706f3f907b40dfb23fcaa90915f082\setup.py:114: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
      import imp

    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:

      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install scipy`   (last SciPy release on PyPI)

    lapack_opt_info:
    lapack_mkl_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries mkl_rt not found in ['c:\\users\\rossp\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\rossp\\appdata\\local\\programs\\python\\python39\\libs']
      NOT AVAILABLE

    openblas_lapack_info:
      libraries openblas not found in ['c:\\users\\rossp\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\rossp\\appdata\\local\\programs\\python\\python39\\libs']
    get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
    customize GnuFCompiler
    Could not locate executable g77
    Could not locate executable f77
    customize IntelVisualFCompiler
    Could not locate executable ifort
    Could not locate executable ifl
    customize AbsoftFCompiler
    Could not locate executable f90
    customize CompaqVisualFCompiler
    Could not locate executable DF
    customize IntelItaniumVisualFCompiler
    Could not locate executable efl
    customize Gnu95FCompiler
    Could not locate executable gfortran
    Could not locate executable f95
    customize G95FCompiler
    Could not locate executable g95
    customize IntelEM64VisualFCompiler
    customize IntelEM64TFCompiler
    Could not locate executable efort
    Could not locate executable efc
    customize PGroupFlangCompiler
    Could not locate executable flang
    don't know how to compile Fortran code on platform 'nt'
      NOT AVAILABLE

    openblas_clapack_info:
      libraries openblas,lapack not found in ['c:\\users\\rossp\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\rossp\\appdata\\local\\programs\\python\\python39\\libs']
      NOT AVAILABLE

    flame_info:
      libraries flame not found in ['c:\\users\\rossp\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\rossp\\appdata\\local\\programs\\python\\python39\\libs']
      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
      libraries lapack_atlas not found in c:\users\rossp\appdata\local\programs\python\python39\lib
      libraries tatlas,tatlas not found in c:\users\rossp\appdata\local\programs\python\python39\lib
      libraries lapack_atlas not found in C:\
      libraries tatlas,tatlas not found in C:\
      libraries lapack_atlas not found in c:\users\rossp\appdata\local\programs\python\python39\libs
      libraries tatlas,tatlas not found in c:\users\rossp\appdata\local\programs\python\python39\libs
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
      libraries lapack_atlas not found in c:\users\rossp\appdata\local\programs\python\python39\lib
      libraries satlas,satlas not found in c:\users\rossp\appdata\local\programs\python\python39\lib
      libraries lapack_atlas not found in C:\
      libraries satlas,satlas not found in C:\
      libraries lapack_atlas not found in c:\users\rossp\appdata\local\programs\python\python39\libs
      libraries satlas,satlas not found in c:\users\rossp\appdata\local\programs\python\python39\libs
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
      libraries lapack_atlas not found in c:\users\rossp\appdata\local\programs\python\python39\lib
      libraries ptf77blas,ptcblas,atlas not found in c:\users\rossp\appdata\local\programs\python\python39\lib
      libraries lapack_atlas not found in C:\
      libraries ptf77blas,ptcblas,atlas not found in C:\
      libraries lapack_atlas not found in c:\users\rossp\appdata\local\programs\python\python39\libs
      libraries ptf77blas,ptcblas,atlas not found in c:\users\rossp\appdata\local\programs\python\python39\libs
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
      libraries lapack_atlas not found in c:\users\rossp\appdata\local\programs\python\python39\lib
      libraries f77blas,cblas,atlas not found in c:\users\rossp\appdata\local\programs\python\python39\lib
      libraries lapack_atlas not found in C:\
      libraries f77blas,cblas,atlas not found in C:\
      libraries lapack_atlas not found in c:\users\rossp\appdata\local\programs\python\python39\libs
      libraries f77blas,cblas,atlas not found in c:\users\rossp\appdata\local\programs\python\python39\libs
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

    lapack_info:
      libraries lapack not found in ['c:\\users\\rossp\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\rossp\\appdata\\local\\programs\\python\\python39\\libs']
      NOT AVAILABLE

    c:\users\rossp\appdata\local\programs\python\python39\lib\site-packages\numpy\distutils\system_info.py:1849: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      return getattr(self, '_calc_info_{}'.format(name))()
    lapack_src_info:
      NOT AVAILABLE

    c:\users\rossp\appdata\local\programs\python\python39\lib\site-packages\numpy\distutils\system_info.py:1849: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      return getattr(self, '_calc_info_{}'.format(name))()
      NOT AVAILABLE

    Running from scipy source directory.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Rossp\AppData\Local\Temp\pip-install-ci31gds8\scipy_7d706f3f907b40dfb23fcaa90915f082\setup.py", line 474, in <module>
        setup_package()
      File "C:\Users\Rossp\AppData\Local\Temp\pip-install-ci31gds8\scipy_7d706f3f907b40dfb23fcaa90915f082\setup.py", line 470, in setup_package
        setup(**metadata)
      File "c:\users\rossp\appdata\local\programs\python\python39\lib\site-packages\numpy\distutils\core.py", line 135, in setup
        config = configuration()
      File "C:\Users\Rossp\AppData\Local\Temp\pip-install-ci31gds8\scipy_7d706f3f907b40dfb23fcaa90915f082\setup.py", line 388, in configuration
        config.add_subpackage('scipy')
      File "c:\users\rossp\appdata\local\programs\python\python39\lib\site-packages\numpy\distutils\misc_util.py", line 1019, in add_subpackage
        config_list = self.get_subpackage(subpackage_name, subpackage_path,
      File "c:\users\rossp\appdata\local\programs\python\python39\lib\site-packages\numpy\distutils\misc_util.py", line 985, in get_subpackage
        config = self._get_configuration_from_setup_py(
      File "c:\users\rossp\appdata\local\programs\python\python39\lib\site-packages\numpy\distutils\misc_util.py", line 927, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\setup.py", line 15, in configuration
        config.add_subpackage('linalg')
      File "c:\users\rossp\appdata\local\programs\python\python39\lib\site-packages\numpy\distutils\misc_util.py", line 1019, in add_subpackage
        config_list = self.get_subpackage(subpackage_name, subpackage_path,
      File "c:\users\rossp\appdata\local\programs\python\python39\lib\site-packages\numpy\distutils\misc_util.py", line 985, in get_subpackage
        config = self._get_configuration_from_setup_py(
      File "c:\users\rossp\appdata\local\programs\python\python39\lib\site-packages\numpy\distutils\misc_util.py", line 927, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\linalg\setup.py", line 19, in configuration
        raise NotFoundError('no lapack/blas resources found')
    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\rossp\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Rossp\\AppData\\Local\\Temp\\pip-install-ci31gds8\\scipy_7d706f3f907b40dfb23fcaa90915f082\\setup.py'"'"'; __file__='"'"'C:\\Users\\Rossp\\AppData\\Local\\Temp\\pip-install-ci31gds8\\scipy_7d706f3f907b40dfb23fcaa90915f082\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Rossp\AppData\Local\Temp\pip-record-es5qji36\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\rossp\appdata\local\programs\python\python39\Include\scipy' Check the logs for full command output.

**Comment by hubortje** [comment]
Excuse me to be this blunt, but this is a mess.

What is your problem?
When did this occur?
How did you set up?
If you want help a question or a description of the occured problem, rather than the raw error code, would have been more helpful.

It looks like you're using scipy.py to install packages. This is not best practice. Try to use `pip install package_name_goes_here`.
I highly recommend to use an Anaconda Environment. It is easier to collect and maintain the packages.
