### ISSUE TITLE
OSError: sndfile library not found

### ISSUE THREAD

**Issue by kshoemoney** [msieg/deep-visualizer#27]
I got this message when I tried to run the visualizer. Anyone know what I should do? I am on a mac running macOS Monterey

`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/soundfile.py", line 142, in <module>
    raise OSError('sndfile library not found')
OSError: sndfile library not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kjzoosh/deep-music-visualizer/visualize.py", line 1, in <module>
    import librosa
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/librosa/__init__.py", line 209, in <module>
    from . import core
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/librosa/core/__init__.py", line 6, in <module>
    from .audio import *  # pylint: disable=wildcard-import
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/librosa/core/audio.py", line 8, in <module>
    import soundfile as sf
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/soundfile.py", line 162, in <module>
    _snd = _ffi.dlopen(_os.path.join(
OSError: cannot load library '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_soundfile_data/libsndfile.dylib': dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_soundfile_data/libsndfile.dylib, 0x0002): tried: '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_soundfile_data/libsndfile.dylib' (no such file)`

**Comment by hubortje** [comment]
Hey @kshoemoney,

you're missing the librosa module in your Python environment. Be sure to install it via pip prior to running the script.

Edit: Even better to run `pip install -r requirements.txt` prior to running the script. It will install all required modules.
