### ISSUE TITLE
Error code 12 (Cannot allocate memory)

### ISSUE THREAD

**Issue by DaWe35** [msieg/deep-visualizer#3]
`python3 visualize.py --song ooo002.mp3 --resolution 512`

**VPS:**
- 6 core
- 16 GB RAM
- 50 GB+ free SSD sapce
- Ubuntu 18.04

```
Generating frames

  0%|                                                                                                                                                                 | 0/14 [00:00<?, ?it/s]Traceback (most recent call last):
  File "visualize.py", line 382, in <module>
    output = model(noise_vector, class_vector, truncation)
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/pytorch_pretrained_biggan/model.py", line 295, in forward
    z = self.generator(cond_vector, truncation)
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/pytorch_pretrained_biggan/model.py", line 239, in forward
    z = layer(z, cond_vector, truncation)
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/pytorch_pretrained_biggan/model.py", line 190, in forward
    x = self.conv_3(x)
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: [enforce fail at CPUAllocator.cpp:64] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 4026531840 bytes. Error code 12 (Cannot allocate memory)

  0%|                                                                                                                                                                 | 0/14 [01:36<?, ?it/s]
```

**Comment by mhsharifi96** [comment]
same problem ! :/
when try run occur error ` can't allocate memory` 

what can I solve it?

**Comment by didinium** [comment]
have the same problem over here

**Comment by illtellyoulater** [comment]
same thing here, anyone manged to fix this?

EDIT: Ah ok, just saw there's a PR that could fix it.

**Comment by didinium** [comment]
I didn't have enough ram. You could either get more ram or modify the code
so the arrays aren't stored in ram

**Comment by illtellyoulater** [comment]
I could make it work using this updated fork which includes this and other fixes, in addition to a couple more features: https://github.com/zlattala/deep-music-visualizer

**Comment by DaWe35** [comment]
Thanks @illtellyoulater, it works fine for me, except is uses 0% of my GPU. How can I make it run on GPU instead of CPU?

**Comment by illtellyoulater** [comment]
@DaWe35 

**If you are using the code from the forked repository then you should open an issue about that on the forked repository.** 

That said, I am not observing the issue you are reporting, but usually when you see the CPU being used in place of the GPU it means you installed a wrong version of torch. To make sure everything works as expected please make sure to follow the forked repository package requirements and installing instructions.

**Comment by DaWe35** [comment]
You're right, but I don't think this issue is related to the new fork. With conda, I was able to use my GPU, so yes, it was something with the version of python/torch/env.
My next question is if there is a 1080p/4k pretrained model, and if not, how do I train it? 😄
